"""MarkdownExporter — export session as a readable report."""
from __future__ import annotations

from pathlib import Path

from codepulse.session.models import Session


class MarkdownExporter:
    def __init__(self, session: Session, session_dir: Path) -> None:
        self._session = session
        self._session_dir = session_dir

    def export(self, output_path: Path) -> None:
        lines: list[str] = []
        s = self._session

        lines.append(f"# CodePulse Session: {s.project_name}")
        lines.append(f"**Date:** {s.session_date}  ")
        lines.append(f"**Project:** `{s.project_path}`  ")
        lines.append(f"**Turns:** {s.turn_count}  ")
        lines.append("")

        for turn in s.turns:
            lines.append(f"---")
            lines.append(f"## Turn {turn.turn_index} — {turn.timestamp.strftime('%H:%M:%S UTC')}")
            lines.append(f"**Agent slot:** {turn.agent_slot + 1}/3  ")
            lines.append("")
            lines.append(f"**You:** {turn.user_message}")
            lines.append("")
            lines.append("**Claude:**")
            lines.append("")
            lines.append(turn.assistant_message)
            lines.append("")

            if turn.synopsis:
                lines.append("**Subagent Synopsis:**")
                lines.append(turn.synopsis)
                lines.append("")

            if turn.diff_path:
                diff_text = self._load_diff(turn.diff_path)
                if diff_text:
                    lines.append("**Diff:**")
                    lines.append("```diff")
                    lines.append(diff_text[:4000])
                    if len(diff_text) > 4000:
                        lines.append(f"... (truncated, {len(diff_text)} chars total)")
                    lines.append("```")
                    lines.append("")

        # Heatmap summary
        lines.append("---")
        lines.append("## Final Heat Map")
        lines.append("")
        lines.append("| File | Touches | Lines Changed |")
        lines.append("|------|---------|---------------|")
        # Load latest heatmap if exists
        heatmaps = sorted(self._session_dir.glob("heatmaps/*-heatmap.json"))
        if heatmaps:
            try:
                from codepulse.heatmap.models import HeatMapState
                state = HeatMapState.model_validate_json(heatmaps[-1].read_text())
                sorted_entries = sorted(
                    state.entries.values(),
                    key=lambda e: e.lines_changed,
                    reverse=True,
                )
                for entry in sorted_entries[:20]:
                    lines.append(f"| `{entry.path}` | {entry.touch_count} | {entry.lines_changed} |")
            except Exception:
                lines.append("| — | — | — |")
        else:
            lines.append("| No data | — | — |")

        lines.append("")
        lines.append("---")
        lines.append("*Generated by CodePulse*")

        output_path.write_text("\n".join(lines))

    def _load_diff(self, diff_path: str) -> str:
        try:
            return Path(diff_path).read_text()
        except Exception:
            return ""
